### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by justintg** [justintg/OpenBudget#6]
### v0.1
**Budget**
- [x] Create Budget
- [x] Set Budget Currency
- [x] Set Budget Currency Number Format
- [ ] Budget Currency Format is used in WPF Application

**Accounts**
- [x] Add an account w/ Initial Balance
- [x] Set Account Type
- [x] Set Budgeting Type (On-Budget/Off-Budget)
- [ ] Can reconcile an account

**Transactions**
- [x] Add a transaction
- [x] Edit a transaction
- [x] Delete a transaction
- [x] Transaction can be a Transfer
- [x] Updating Amount of Transfer updates both sides of the Transfer
- [x] Transaction Category can be set
- [x] Split Transactions Supported(in view and edit mode)
- [x] Sub Transaction Transfer
- [ ] Transaction state (cleared/uncleared)
- [ ] Transaction validation is visible when transaction is in an error state

**Categories**
- [x] Can add a Category to a Master Category
- [x] Can add a MasterCategory to the budget
- [x] Can reorder MasterCategories and Categories
- [x] Can add/update a note on a Category
- [x] Can rename a Master Category
- [x] Can rename a Category

**Budget View**
- [x] Virtualized Budget View(all BudgetViewMonths "exist" but arent materialized until needed for display.
- [x] Can updated Budgeted amount on CategoryMonth which triggers a recalculation
- [x] Master Category summary row
- [ ] Right arrow red(transfer category balance to next month) on CategoryMonth
- [x] Add/update a note on CategoryMonth
- [x] Budget Month header
- [x] Proper formatting/colors on BudgetView rows and month headers
- [x] Drag and Drop on BudgetView can scroll the view
- [x] Master Category Expander

**Storage Format**
- [x] Have a basic cross-platform SQLite storage format for the budget
- [x] Have an in-memory BudgetStore to be the reference implementation of IBudgetStore and for testing purposes
- [x] Standard EventStream serialization format 
- [ ] Implement IBudgetViewCache extension for SQLite budget store that does most of the calculation and grouping in SQL

### v0.2
- [ ] Transaction virtualization at data level(stream from the database rather than load an entire account into memory)
- [ ] Configurable sort order on Transaction grid
- [ ] Storage optimization - new VectorClock binary format
- [ ] Storage optimization - Event data compression using a predetermined deflate dictionary
- [ ] Implement event sorting for synchronization in SQLite
- [ ] Optimize BudgetViewCalculator to do partial re-calculation rather than a full calculation when possible
- [ ] File directory synchronization
- [ ] YNAB4 Import
